import React, { Component } from 'react'
import classNames from 'classnames'
import Button from '../Button'
import ButtonGroup from '../ButtonGroup'
import Textarea from '../Form/Textarea'
import { getWindowSize, getAttributeForCurrentSize } from '../../utils/size'
import style from './style.less'
import colors from '../../foundation/colors.less'

export default class Text extends Component {
   static propTypes = {
      children: React.PropTypes.node,
      className: React.PropTypes.string,
      color: React.PropTypes.string,
      editable: React.PropTypes.bool,
      editorCancelButtonText: React.PropTypes.string,
      editorDoneButtonText: React.PropTypes.string,
      editorState: React.PropTypes.oneOf(['ready', 'pending']),
      editorOnCancel: React.PropTypes.func,
      editorOnDone: React.PropTypes.func,
      editorShowEditButton: React.PropTypes.bool,
      editorValue: React.PropTypes.string,
      editing: React.PropTypes.bool,
      size: React.PropTypes.string,
      uppercase: React.PropTypes.bool,
      weight: React.PropTypes.string
   }

   static defaultProps = {
      editable: false,
      editorCancelButtonText: 'Cancel',
      editorDoneButtonText: 'Done',
      editorState: 'ready',
      editorShowEditButton: false,
      editing: false,
      size: '3',
      weight: 'normal'
   }

   static contextTypes = {
      OIOStyles: React.PropTypes.object
   }

   constructor(props) {
      super(props)

      this.handleChange = this.handleChange.bind(this)
      this.handleEditCancel = this.handleEditCancel.bind(this)
      this.handleEditClick = this.handleEditClick.bind(this)
      this.handleEditDone = this.handleEditDone.bind(this)
      this.windowSizeUpdated = this.windowSizeUpdated.bind(this)

      this.state = {
         editing: props.editing,
         editorValue: props.editorValue,
         size: getWindowSize()
      }
   }

   // =====================================================
   // Lifecycle
   // =====================================================

   componentDidMount() {
      window.addEventListener('resize', this.windowSizeUpdated, false)
   }

   componentWillReceiveProps(nextProps) {
      const stateChangeRequired = ['editable', 'editing', 'editorState', 'editorValue'].some(prop => (
         typeof nextProps[prop] !== 'undefined' && this.state[prop] !== nextProps[prop]
      ))

      if (stateChangeRequired) {
         this.setState({
            editable: nextProps.editable,
            editing: nextProps.editing,
            editorState: nextProps.editorState,
            editorValue: nextProps.editorValue
         })
      }
   }

   componentDidUpdate() {
      // this.editor is a ref generated by the editable portion,
      // when the componentDidUpdate, auto-size the textarea
      if (this.editor) {
         const textarea = this.editor.parentNode.getElementsByTagName('textarea')[0]
         this.adjustTextareaHeight(textarea)
      }
   }

   componentWillUnmount() {
      window.removeEventListener('resize', this.windowSizeUpdated)
   }

   // =====================================================
   // Utils
   // =====================================================

   adjustTextareaHeight(textarea) {
      if (textarea) {
         // Set to auto first to "reset" to avoid browser jank
         textarea.style.height = 'auto'
         textarea.style.height = `${textarea.scrollHeight + 5}px`
      }
   }

   // =====================================================
   // Event Handlers
   // =====================================================

   handleChange(event) {
      this.adjustTextareaHeight(event.target)

      let value = event.target.value

      // Remove line-breaks from textarea value
      value = value.replace(/\n/g, '')

      this.setState({ editorValue: value })
   }

   handleEditCancel() {
      if (this.props.editorOnCancel) this.props.editorOnCancel(this.state.editorValue)

      this.setState({ editorValue: this.props.editorValue })
   }

   handleEditClick(event) {
      this.setState({
         editorValue: this.props.editorValue,
         editing: true
      })
   }

   handleEditDone() {
      if (this.props.editorOnDone) this.props.editorOnDone(this.state.editorValue)
   }

   windowSizeUpdated() {
      const windowSize = getWindowSize()
      this.setState({ size: windowSize })
   }

   // =====================================================
   // Edit Action Buttons JSX (Editable Text Only)
   // =====================================================

   editButtonsReady() {
      return (
         <ButtonGroup align="right">
            <Button
               onClick={this.handleEditCancel}
               name={this.props.editorCancelButtonText}
               size="tiny"
               color="#CCC"
            />
            <Button
               onClick={this.handleEditDone}
               name={this.props.editorDoneButtonText}
               size="tiny"
            />
         </ButtonGroup>
      )
   }

   editButtonsPending() {
      return (
         <ButtonGroup align="right">
            <Button
               onClick={this.handleEditDone}
               name="Done"
               size="tiny"
               mode="loading"
            />
         </ButtonGroup>
      )
   }

   // =====================================================
   // Render
   // =====================================================

   render() {
      const fontSize = `textSize${getAttributeForCurrentSize(this.state.size, this.props.size)}`
      const textStyle = {}

      const textClasses = [
         style[fontSize],
         style[this.props.weight],
         colors[this.props.color],
         this.props.className
      ]

      if (this.props.uppercase) {
         textClasses.push(style.uppercase)
      }

      const editing = this.props.editable && this.state.editing
      const editorValue = this.props.editable && this.props.editorValue

      const showEditButton = (
         !this.state.editing &&
         this.props.editable &&
         this.props.editorShowEditButton
      )

      const editActionButtons = this.props.editorState === 'ready'
         ? this.editButtonsReady()
         : this.editButtonsPending()

      let content = <span>{this.props.children || editorValue}</span>
      if (editing) {
         content = (
            <div ref={(editor) => { this.editor = editor }}>
               <Textarea
                  className={style.editTextarea}
                  onChange={this.handleChange}
                  value={this.state.editorValue}
                  placeholder="Add text..."
                  disabled={this.state.editorState === 'pending'}
               />
               {editActionButtons}
            </div>
         )
      }

      return (
         <div className={classNames(textClasses)} style={textStyle}>
            {showEditButton && (
               <Button
                  onClick={this.handleEditClick}
                  className={style.editButton}
                  icon="ion-edit"
                  size="tiny"
               />
            )}
            {content}
         </div>
      )
   }
}
